### ISSUE TITLE
How can we change the JEITA T1---T5 temperature value in bq25892 ?

### ISSUE THREAD

**Issue by yjxch** [tibms/bq2589x#1]
Hi ti ,

How can we change the JEITA T1---T5 temperature value in bq25892 ?

**Comment by tibms** [comment]
There is no way to change it by software, it's not configurable.

Thanks,
Falong

-Sent from mobile

在 2017年3月22日，上午10:08，zhangxch <notifications@github.com<mailto:notifications@github.com>> 写道：


Hi ti ,

How can we change the JEITA T1---T5 temperature value in bq25892 ?

―

**Comment by yjxch** [comment]
ok thanks!
